### ISSUE TITLE
On latest update: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'

### ISSUE THREAD

**Issue by marcobra** [enzococca/totalopenstationToQgis#2]
hi, with last update, i get this error:
thank
```
Impossibile caricare il plugin 'totalopenstationToQgis' a causa di un errore chiamando il metodo classFactory() 

TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/totalopenstationToQgis/__init__.py", line 89, in classFactory
    from .totalstation import Totalopenstation
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/totalopenstationToQgis/totalstation.py", line 34, in 
    from .totalstation_dialog import TotalopenstationDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/totalopenstationToQgis/totalstation_dialog.py", line 44, in 
    FORM_CLASS, _ = loadUiType(os.path.join(os.path.dirname(__file__),'totalstation_dialog_base.ui'))
  File "/usr/lib/python3/dist-packages/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 203, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 293, in 
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/resources_rc.py", line 1251, in 
    qInitResources()
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/resources_rc.py", line 1242, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct,
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'

```

**Comment by marcobra** [comment]
This bug is not directly related to totalopenstationToQgis but to compile resource of qgis2web:
https://github.com/tomchadwin/qgis2web/issues/1007

not sure why the error report also report on totalopenstationToQgis, but dressing the qgis2web made totalopenstationToQgis working
