### ISSUE TITLE
ModuleNotFoundError: No module named 'resources_rc' 

### ISSUE THREAD

**Issue by Ihluvathar** [enzococca/totalopenstationToQgis#3]
Hello, when lanching the addon on qgis i have this issue :

ModuleNotFoundError: No module named 'resources_rc' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/xavie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\totalopenstationToQgis\__init__.py", line 89, in classFactory
    from .totalstation import Totalopenstation
  File "C:\Users/xavie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/xavie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\totalopenstationToQgis\totalstation.py", line 34, in 
    from .totalstation_dialog import TotalopenstationDialog
  File "C:\Users/xavie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/xavie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\totalopenstationToQgis\totalstation_dialog.py", line 44, in 
    FORM_CLASS, _ = loadUiType(os.path.join(os.path.dirname(__file__),'totalstation_dialog_base.ui'))
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 294, in 
  File "C:\Users/xavie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'resources_rc'

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.26.0-Buenos Aires Buenos Aires, 0aece2818e

any idea to fix this issue ?
thanks !

**Comment by enzococca** [comment]
Hi
thanks for the issue.
Do you use the windows OS right?

I will fix it, it is a question about the uic

E

Il gio 7 lug 2022, 16:29 Ihluvathar ***@***.***> ha scritto:

**Comment by Ihluvathar** [comment]
Hello i’m using the latest Windows os
I fixed the issue by copying all the files into the ext-libs file and the ext-libs/totalopenstation file. 😊

I Wonder if it’s possible to connect my Leica TS06 plus via Bluetooth or i must connect via the usb interface ?
I’m on the field actually and looking for a total control of the total station via Qgis it would be insane !

Thanks a lot !


De : enzo
Envoyé le :jeudi 7 juillet 2022 15:41
À : enzococca/totalopenstationToQgis
Cc : Ihluvathar; Author
Objet :Re: [enzococca/totalopenstationToQgis] ModuleNotFoundError: No modulenamed 'resources_rc' (Issue #3)

Hi
thanks for the issue.
Do you use the windows OS right?

I will fix it, it is a question about the uic

E

Il gio 7 lug 2022, 16:29 Ihluvathar ***@***.***> ha scritto:

**Comment by enzococca** [comment]
hi, sounds good but im not understand what you did.

Yes you should connect via bloutooth. I tryed just with one total station and works.

let me know if forks for you

E

**Comment by Ihluvathar** [comment]
Hello, 
when i check the ports it doesnt find any

__
Wait a moment....
Ports found:
[]
__

If you have any tips it would be really nice,
( I use to work with field Genius on my Windows tablet to control the machine )
Have a nice day ! 
Cheers from the field in Corsica 

De : enzo
Envoyé le :jeudi 7 juillet 2022 17:26
À : enzococca/totalopenstationToQgis
Cc : Ihluvathar; Author
Objet :Re: [enzococca/totalopenstationToQgis] ModuleNotFoundError: No modulenamed 'resources_rc' (Issue #3)

hi, sounds good but im not understand what you did.
Yes you should connect via bloutooth. I tryed just with one total station and works.
let me know if forks for you
E

**Comment by enzococca** [comment]
Hi, do you use the option blutooth in the plugin?

Il ven 8 lug 2022, 11:04 Ihluvathar ***@***.***> ha scritto:

**Comment by Ihluvathar** [comment]
I checked the « custom_bluetooth » in the model selection but in the « port selection » i can’t see any appearing (i may dont know how to name the Bluetooth port), also when i check port the soft d’ont find any… (my machine is connected to the computer)


De : enzo
Envoyé le :vendredi 8 juillet 2022 11:10
À : enzococca/totalopenstationToQgis
Cc : Ihluvathar; Author
Objet :Re: [enzococca/totalopenstationToQgis] ModuleNotFoundError: No modulenamed 'resources_rc' (Issue #3)

Hi, do you use the option blutooth in the plugin?

Il ven 8 lug 2022, 11:04 Ihluvathar ***@***.***> ha scritto:
